export default [
  { id: 1, description: "uoba", value: 21000, positive: true },
  { id: 2, description: "carai", value: 1500, positive: true },
  { id: 3, description: "tres", value: 20, positive: false },
  { id: 4, description: "a", value: 35, positive: false },
  { id: 5, description: "b", value: 200, positive: true },
  { id: 6, description: "c", value: 37, positive: true },
  { id: 7, description: "sem criatividade", value: 1290, positive: false },
  { id: 8, description: "eita bicho", value: 250, positive: true },
  { id: 9, description: "testando", value: 90, positive: false },
  { id: 10, description: "aiai", value: 45, positive: false },
  { id: 10, description: "aiai", value: 45, positive: false },
  { id: 10, description: "aiai", value: 45, positive: false },
  { id: 10, description: "aiai", value: 45, positive: false },
  { id: 10, description: "aiai", value: 45, positive: false },
  { id: 10, description: "aiai", value: 45, positive: false },
  { id: 10, description: "aiai", value: 45, positive: false },
  { id: 10, description: "aiai", value: 45, positive: false },
  { id: 10, description: "aiai", value: 45, positive: false },
  { id: 10, description: "aiai", value: 45, positive: false },
  { id: 10, description: "aiai", value: 45, positive: false },
  { id: 10, description: "aiai", value: 45, positive: false },
];
